//This is a scripted pipeline syntax and not the declarative pipeline syntax
node('docker'){
    checkout scm
    sh '''cat > docker-compose.staging.yml <<EOL
version: "3.6"
services:
  app:
    labels:
      - "traefik.frontend.rule=Host:staging.docker.localhost;PathPrefixStrip:/build-${BUILD_NUMBER}"
      - "traefik.backend=app-${BUILD_NUMBER}"
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME:-jenkins_staging}_traefik"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.tags=${COMPOSE_PROJECT_NAME:-jenkins_staging}"

EOL'''
    sh 'docker-compose -f docker-compose.app.yml -f docker-compose.staging.yml up -d'
    sh 'echo new Staging environment Now available at https://staging.docker.localhost/build-${BUILD_NUMBER}/hello'
}